/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PACKET_HEADER, packet_header_t, AUTO)


PB_BIND(SIMPLE_SENSOR_READING, simple_sensor_reading_t, AUTO)


PB_BIND(SENSOR_READING, sensor_reading_t, AUTO)


PB_BIND(SENSOR_READING_PAYLOAD, sensor_reading_payload_t, AUTO)


PB_BIND(SENSOR_CONFIG, sensor_config_t, AUTO)


PB_BIND(SD_CARD_STATE, sd_card_state_t, AUTO)


PB_BIND(MARK_STATE, mark_state_t, AUTO)


PB_BIND(MARK_PACKET, mark_packet_t, AUTO)


PB_BIND(DISCOVERED_DEVICES, discovered_devices_t, AUTO)


PB_BIND(DISCOVERED_DEVICES_DEVICE, discovered_devices_device_t, AUTO)


PB_BIND(BATTERY_STATE, battery_state_t, AUTO)


PB_BIND(SYSTEM_INFO_PACKET, system_info_packet_t, 2)


PB_BIND(AUDIO_COMPRESSION, audio_compression_t, AUTO)


PB_BIND(AUDIO_CONFIG, audio_config_t, AUTO)


PB_BIND(SCHEDULE_CONFIG, schedule_config_t, AUTO)


PB_BIND(LOW_POWER_CONFIG, low_power_config_t, AUTO)


PB_BIND(CAMERA_CONTROL, camera_control_t, AUTO)


PB_BIND(NETWORK_STATE, network_state_t, AUTO)


PB_BIND(CONFIG_PACKET, config_packet_t, 2)


PB_BIND(SPECIAL_FUNCTION, special_function_t, AUTO)


PB_BIND(PACKET, packet_t, 2)








