/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "uwb_i2c_proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BEECAM_UWB_I2C_UNIT, beecam_uwb_i2c_unit_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_PEER_ADDRESS, beecam_uwb_i2c_peer_address_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DEVICE_INFO, beecam_uwb_i2c_device_info_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DEVICE_INFO_UWB_INFO, beecam_uwb_i2c_device_info_uwb_info_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DEVICE_INFO_BLUETOOTH_INFO, beecam_uwb_i2c_device_info_bluetooth_info_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DEVICE_INFO_FIRMWARE_BUILD_INFO, beecam_uwb_i2c_device_info_firmware_build_info_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_UPLINK, beecam_uwb_i2c_uplink_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DOWNLINK, beecam_uwb_i2c_downlink_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DOWNLINK_ERROR, beecam_uwb_i2c_downlink_error_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DOWNLINK_STATUS, beecam_uwb_i2c_downlink_status_t, AUTO)


PB_BIND(BEECAM_UWB_I2C_DOWNLINK_PTP_RESULT, beecam_uwb_i2c_downlink_ptp_result_t, AUTO)




