/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PacketHeader, PacketHeader, AUTO)


PB_BIND(SimpleSensorReading, SimpleSensorReading, AUTO)


PB_BIND(SensorReading, SensorReading, AUTO)


PB_BIND(SensorReading_Payload, SensorReading_Payload, AUTO)


PB_BIND(SensorConfig, SensorConfig, AUTO)


PB_BIND(SDCardState, SDCardState, AUTO)


PB_BIND(MarkState, MarkState, AUTO)


PB_BIND(MarkPacket, MarkPacket, AUTO)


PB_BIND(SystemInfoPacket, SystemInfoPacket, AUTO)


PB_BIND(AudioCompression, AudioCompression, AUTO)


PB_BIND(AudioConfig, AudioConfig, AUTO)


PB_BIND(ScheduleConfig, ScheduleConfig, AUTO)


PB_BIND(DiscoveredDevices, DiscoveredDevices, AUTO)


PB_BIND(DiscoveredDevices_Device, DiscoveredDevices_Device, AUTO)


PB_BIND(ConfigPacket, ConfigPacket, AUTO)


PB_BIND(SpecialFunction, SpecialFunction, AUTO)


PB_BIND(Packet, Packet, AUTO)







